version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
    networks:
      - hc-network
  mongo:
    image: mongo
    networks:
      - hc-network
    command: "--smallfiles --logpath=/dev/null"

networks:
  hc-network:
